// Enums matching backend sub_models

export enum AccessLevel {
  ADMIN = 1,
  DEPTHEAD = 2,
}

export enum MembershipType {
  HEAD = "HEAD",
  MEMBER = "MEMBER",
}

export enum AttendanceType {
  PRESENT = "PRESENT",
  LATE = "LATE",
  EXCUSED = "EXCUSED",
}

export enum TimeOutType {
  ONTIME = "On-Time",
  EARYLEAVE = "Early Leave",
  FORGOT = "Forgot",
  EXCUSED = "Excused",
}

export enum LogType {
  // System
  CLEAN_LOG = "CLEAN_LOG",

  // Authentication
  USER_LOGIN = "USER_LOGIN",
  USER_LOGIN_FAILED = "USER_LOGIN_FAILED",
  USER_LOGOUT = "USER_LOGOUT",

  // User Management
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  USER_DISABLED = "USER_DISABLED",
  USER_ENABLED = "USER_ENABLED",
  ACCESS_LEVEL_CHANGED = "ACCESS_LEVEL_CHANGED",
  PASSWORD_CHANGED = "PASSWORD_CHANGED",

  // OAuth
  OAUTH_LINKED = "OAUTH_LINKED",
  OAUTH_LOGIN = "OAUTH_LOGIN",

  // Attendance & Scheduling
  VOLUNTEER_TIMED_IN = "VOLUNTEER_TIMED_IN",
  VOLUNTEER_TIMED_OUT = "VOLUNTEER_TIMED_OUT",
  ATTENDANCE_STATUS_UPDATED = "ATTENDANCE_STATUS_UPDATED",
  VOLUNTEER_SCHEDULED = "VOLUNTEER_SCHEDULED",
  VOLUNTEER_UNSCHEDULED = "VOLUNTEER_UNSCHEDULED",

  // Volunteer Management
  VOLUNTEER_CREATED = "VOLUNTEER_CREATED",
  VOLUNTEER_UPDATED = "VOLUNTEER_UPDATED",
  VOLUNTEER_DELETED = "VOLUNTEER_DELETED",
  VOLUNTEER_DISABLED = "VOLUNTEER_DISABLED",
  VOLUNTEER_ENABLED = "VOLUNTEER_ENABLED",

  // Event Management
  EVENT_CREATED = "EVENT_CREATED",
  EVENT_UPDATED = "EVENT_UPDATED",
  EVENT_DELETED = "EVENT_DELETED",
  EVENT_CANCELLED = "EVENT_CANCELLED",
  EVENT_DEPARTMENT_ADDED = "EVENT_DEPARTMENT_ADDED",
  EVENT_DEPARTMENT_REMOVED = "EVENT_DEPARTMENT_REMOVED",

  // Department Management
  DEPARTMENT_CREATED = "DEPARTMENT_CREATED",
  DEPARTMENT_UPDATED = "DEPARTMENT_UPDATED",
  DEPARTMENT_DELETED = "DEPARTMENT_DELETED",
  DEPARTMENT_MEMBER_ADDED = "DEPARTMENT_MEMBER_ADDED",
  DEPARTMENT_MEMBER_REMOVED = "DEPARTMENT_MEMBER_REMOVED",
  DEPARTMENT_ROLE_CHANGED = "DEPARTMENT_ROLE_CHANGED",

  // Batch Operations
  BATCH_IMPORT_STARTED = "BATCH_IMPORT_STARTED",
  BATCH_IMPORT_COMPLETED = "BATCH_IMPORT_COMPLETED",
  BATCH_IMPORT_FAILED = "BATCH_IMPORT_FAILED",
  BATCH_CONFLICT_RESOLVED = "BATCH_CONFLICT_RESOLVED",

  // System & Data Access
  SENSITIVE_DATA_ACCESSED = "SENSITIVE_DATA_ACCESSED",
  SYSTEM_ERROR = "SYSTEM_ERROR",
  CONFIGURATION_CHANGED = "CONFIGURATION_CHANGED",
}
