package sub_model

type LogType string

const (
	// System
	CLEANLOG LogType = "CLEAN_LOG"

	// Authentication
	USER_LOGIN        LogType = "USER_LOGIN"
	USER_LOGIN_FAILED LogType = "USER_LOGIN_FAILED"
	USER_LOGOUT       LogType = "USER_LOGOUT"

	// User Management
	USER_CREATED         LogType = "USER_CREATED"
	USER_UPDATED         LogType = "USER_UPDATED"
	USER_DISABLED        LogType = "USER_DISABLED"
	USER_ENABLED         LogType = "USER_ENABLED"
	ACCESS_LEVEL_CHANGED LogType = "ACCESS_LEVEL_CHANGED"
	PASSWORD_CHANGED     LogType = "PASSWORD_CHANGED"

	// OAuth
	OAUTH_LINKED LogType = "OAUTH_LINKED"
	OAUTH_LOGIN  LogType = "OAUTH_LOGIN"

	// Attendance & Scheduling
	VOLUNTEER_TIMED_IN        LogType = "VOLUNTEER_TIMED_IN"
	VOLUNTEER_TIMED_OUT       LogType = "VOLUNTEER_TIMED_OUT"
	ATTENDANCE_STATUS_UPDATED LogType = "ATTENDANCE_STATUS_UPDATED"
	VOLUNTEER_SCHEDULED       LogType = "VOLUNTEER_SCHEDULED"
	VOLUNTEER_UNSCHEDULED     LogType = "VOLUNTEER_UNSCHEDULED"

	// Volunteer Management
	VOLUNTEER_CREATED  LogType = "VOLUNTEER_CREATED"
	VOLUNTEER_UPDATED  LogType = "VOLUNTEER_UPDATED"
	VOLUNTEER_DELETED  LogType = "VOLUNTEER_DELETED"
	VOLUNTEER_DISABLED LogType = "VOLUNTEER_DISABLED"
	VOLUNTEER_ENABLED  LogType = "VOLUNTEER_ENABLED"

	// Event Management
	EVENT_CREATED            LogType = "EVENT_CREATED"
	EVENT_UPDATED            LogType = "EVENT_UPDATED"
	EVENT_DELETED            LogType = "EVENT_DELETED"
	EVENT_CANCELLED          LogType = "EVENT_CANCELLED"
	EVENT_DEPARTMENT_ADDED   LogType = "EVENT_DEPARTMENT_ADDED"
	EVENT_DEPARTMENT_REMOVED LogType = "EVENT_DEPARTMENT_REMOVED"

	// Department Management
	DEPARTMENT_CREATED        LogType = "DEPARTMENT_CREATED"
	DEPARTMENT_UPDATED        LogType = "DEPARTMENT_UPDATED"
	DEPARTMENT_DELETED        LogType = "DEPARTMENT_DELETED"
	DEPARTMENT_MEMBER_ADDED   LogType = "DEPARTMENT_MEMBER_ADDED"
	DEPARTMENT_MEMBER_REMOVED LogType = "DEPARTMENT_MEMBER_REMOVED"
	DEPARTMENT_ROLE_CHANGED   LogType = "DEPARTMENT_ROLE_CHANGED"

	// Batch Operations
	BATCH_IMPORT_STARTED    LogType = "BATCH_IMPORT_STARTED"
	BATCH_IMPORT_COMPLETED  LogType = "BATCH_IMPORT_COMPLETED"
	BATCH_IMPORT_FAILED     LogType = "BATCH_IMPORT_FAILED"
	BATCH_CONFLICT_RESOLVED LogType = "BATCH_CONFLICT_RESOLVED"

	// System & Data Access
	SENSITIVE_DATA_ACCESSED LogType = "SENSITIVE_DATA_ACCESSED"
	SYSTEM_ERROR            LogType = "SYSTEM_ERROR"
	CONFIGURATION_CHANGED   LogType = "CONFIGURATION_CHANGED"
)

// GetLogTypeCategory returns the category for a given log type
func GetLogTypeCategory(logType LogType) string {
	switch logType {
	case USER_LOGIN, USER_LOGIN_FAILED, USER_LOGOUT:
		return "authentication"
	case USER_CREATED, USER_UPDATED, USER_DISABLED, USER_ENABLED, ACCESS_LEVEL_CHANGED, PASSWORD_CHANGED:
		return "user_management"
	case OAUTH_LINKED, OAUTH_LOGIN:
		return "oauth"
	case VOLUNTEER_TIMED_IN, VOLUNTEER_TIMED_OUT, ATTENDANCE_STATUS_UPDATED, VOLUNTEER_SCHEDULED, VOLUNTEER_UNSCHEDULED:
		return "attendance"
	case VOLUNTEER_CREATED, VOLUNTEER_UPDATED, VOLUNTEER_DELETED, VOLUNTEER_DISABLED, VOLUNTEER_ENABLED:
		return "volunteer_management"
	case EVENT_CREATED, EVENT_UPDATED, EVENT_DELETED, EVENT_CANCELLED, EVENT_DEPARTMENT_ADDED, EVENT_DEPARTMENT_REMOVED:
		return "event_management"
	case DEPARTMENT_CREATED, DEPARTMENT_UPDATED, DEPARTMENT_DELETED, DEPARTMENT_MEMBER_ADDED, DEPARTMENT_MEMBER_REMOVED, DEPARTMENT_ROLE_CHANGED:
		return "department_management"
	case BATCH_IMPORT_STARTED, BATCH_IMPORT_COMPLETED, BATCH_IMPORT_FAILED, BATCH_CONFLICT_RESOLVED:
		return "batch_operations"
	case SENSITIVE_DATA_ACCESSED, SYSTEM_ERROR, CONFIGURATION_CHANGED:
		return "system"
	case CLEANLOG:
		return "system"
	default:
		return "unknown"
	}
}
